config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
      get 'join'
      get 'wait'
      get 'cancel'
      get 'approve/:id', to: 'rooms#approve', as: :approve
      get 'reject/:id', to: 'rooms#reject', as: :reject
    end
    resources :menus, only: [:new, :create, :show]
    resources :schedules, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :room
  has_one_attached :image

  validates :image, presence: true
  validates :cook_name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :menus
  has_many :schedules
  with_options presence: true do
    validates :room_name
    validates :key,  uniqueness: true, length: { minimum: 8 }, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room
  with_options presence: true do
    validates :date
    validates :menu_id
    validates :room_id
  end

  def start_time
    self.date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_one :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @menu = Menu.find(params[:room_id])
    @schedule = Schedule.where(menu_id: @menu.id)
  end

  private

  def menu_params
    params.require(:menu).permit(:cook_name, :memo, :image).merge(room_id: current_user.room_key)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :search_room, only: [:search, :join]

  def index
    if user_signed_in?
      if current_user.waiting_room_key != nil
        redirect_to wait_rooms_path
      elsif current_user.room_key == ""
        redirect_to search_rooms_path
      else
        @room = Room.find(current_user.room_key)
        redirect_to room_path(@room.id)
      end
    end
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      user = User.find(current_user.id)
      user.room_key = @room.id
      user.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def show
    @room = Room.find(current_user.room_key)
    @applies = User.where(waiting_room_key: @room.id)
    @schedule = Schedule.new
    @schedules = Schedule.where(room_id: @room.id)
    @schedules_today = Schedule.where(room_id: @room.id).where(date: Date.today)
  end

  def search
    @rooms = Room.includes(:room)
  end
  
  def join
    @result = @r.result
  end
  
  def wait
    if current_user.waiting_room_key == nil
      search_room
      @room = @r.result
      @room.each do |room|
        current_user.waiting_room_key = room.id
      end
      current_user.save
    else
      @room = [Room.find(current_user.waiting_room_key)]
    end
  end
  
  def cancel
    current_user.waiting_room_key = ""
    current_user.save
    redirect_to root_path
  end
  
  def approve
    delete_waiting
    @room = Room.find(current_user.room_key)
    @user.room_key = @room.id
    if @room.member1 == nil
      @room.member1 = @user.id
    elsif @room.member2 == nil
      @room.member2 = @user.id
    elsif @room.member3 == nil
      @room.member3 = @user.id
    elsif @room.member4 == nil
      @room.member4 = @user.id
    elsif @room.member5 == nil
      @room.member5 = @user.id
    elsif @room.member6 == nil
      @room.member6 = @user.id
    elsif @room.member7 == nil
      @room.member7 = @user.id
    elsif @room.member8 == nil
      @room.member8 = @user.id
    elsif @room.member9 == nil
      @room.member9 = @user.id
    end
    @user.save
    @room.save
    redirect_to root_path
  end
  
  def reject
    delete_waiting
    @user.save
    redirect_to root_path
  end
  
  private
  
  def room_params
    params.require(:room).permit(:room_name, :key, :rule).merge(user_id: current_user.id)
  end
  
  def search_room
    @r = Room.ransack(params[:q])
  end
  
  def delete_waiting
    @user = User.find(params[:id])
    @user.waiting_room_key = ""
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def create
    @room = Room.find(current_user.room_key)
    @schedule = Schedule.new(schedule_params)
    @schedule.save
    redirect_to root_path
  end
  
  def destroy
    @schedule = Schedule.find(params[:room_id])
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:date, :menu_id).merge(room_id: @room.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nanitaberu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/main_header" %>
    <%= yield %>
    <%= render "shared/main_footer" %>
  </body>
</html>

app/views/menus/new.html.erb
<div class="page menu-new-page">
  <div class="page-title">
    <h1 class="title-text">メニュー新規作成</h1>
  </div>
  <div class="create-menu">
    <%= form_with model: [@room, @menu], url: room_menus_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <div class="create-menu-form">
        <div class="create-menu-form-left">
          <%= f.label :料理画像, class: "create-menu-form-label" %>
          <span class="indispensable">必須</span>
        </div>
        <div class="create-menu-form-upload">
          <p>クリックしてファイルをアップロード</p>
          <%= f.file_field :image, id:"create-menu-image" %>
        </div>
      </div>
      <div class="create-menu-form">
        <div class="create-menu-form-left">
          <%= f.label :料理名, class: "create-menu-form-label" %>
          <span class="indispensable">必須</span>
        </div>
        <div class="create-menu-form-right">
          <%= f.text_field :cook_name, class: "create-menu-name", placeholder: "例）カレー" %>
        </div>
      </div>
      <div class="create-menu-form">
        <div class="create-menu-form-left">
          <%= f.label :メモ, class: "create-menu-form-label" %>
        </div>
        <div class="create-menu-form-right">
          <%= f.text_field :memo, class: "create-menu-name", placeholder: "補足があれば入力可" %>
        </div>
      </div>
      <div class='transition-btn'>
        <div class="btn-content">
          <%= f.submit "作成", class:"next-btn" %>
        </div>
        <div class="btn-content">
          <%= link_to 'ルームにもどる', root_path, class:"back-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/show.html.erb
<div class="page menu-show-page">
  <div class="page-title">
    <h1 class="title-text">メニュー</h1>
  </div>
  <div class="show-menu">
    <div>
      <%= image_tag @menu.image, class:"show-menu-img" %>
    </div>
    <table class="menu-show-table">
      <tbody>
        <tr>
          <th class="detail-item">料理名</th>
          <td class="detail-value"><%= @menu.cook_name %></td>
        </tr>
        <tr>
          <th class="detail-item">メモ</th>
          <td class="detail-value"><%= @menu.memo %></td>
        </tr>
        <tr>
          <th class="detail-item">直近の献立日</th>
          <td class="detail-value">
            <% @schedule.order(date: :desc).each do |schedule| %>
              <%= schedule.date %><br>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">献立登場回数</th>
          <td class="detail-value"><%= @schedule.count %></td>
        </tr>
      </tbody>
    </table>
    <div class='transition-btn'>
      <div class="btn-content">
        <%= link_to 'ルームにもどる', root_path, class:"back-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="page top-page">
  <div class="contents">
    <div class="content1">
      <div class="index-img1">
        <%= image_tag "image1.png", class:"log-out-img" %>
      </div>
      <div class="index-sentense1">
        家族・同居人内の専用ルームで献立を登録！<br>
        今日のご飯が何かいつでも確認可能！
      </div>
    </div>
    <div class="content2">
      <div class="index-sentense2">
        登録も簡単！　1分で会員登録！<br>
        登録後はルーム作成or参加！
      </div>
    </div>
    <div class="content3">
      <div class="index-sentense3">
        いつ食べたか・何回食べたかの集計機能あり！<br>
        献立を考える上で参考に！
      </div>
      <div class="index-img3">
        <%= image_tag "image2.png", class:"log-out-img" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/join.html.erb
<div class="page room-search-page">
  <div class="page-title">
    <h1 class="title-text">ルーム検索</h2>
  </div>
  <div class="contents">
    <% if @result.empty? %>
      検索されたルームコードに合致するルーム登録はありません
    <div class="transition-btn">
    <% else %>
      <% @result.each do |result| %>
        <table class="detail-table">  
          <tbody>
            <tr>
              <th class="detail-item">ルームコード</th>
              <td class="detail-value"><%= result.key %></td>
            </tr>
            <tr>
              <th class="detail-item">ルーム名</th>
              <td class="detail-value"><%= result.room_name %></td>
            </tr>
            <tr>
              <th class="detail-item">オーナー</th>
              <td class="detail-value"><%= result.user.name %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
      <%= search_form_for @r, url: wait_rooms_path do |f| %>
        <div class="create-room-form hidden">
          <div class="create-room-form-left">
            <%= f.label :key_eq, "検索用ルームコード（完全一致）", class:"hidden" %>
          </div>
          <div class="create-room-form-right">
            <%= f.text_field :key_eq, required: true, class:"hidden" %>
          </div>
        </div>
        <div class='transition-btn'>
          <div class="btn-content">
            <%= f.submit "入室を申請する", class:"next-btn" %>
          </div>
      <% end %>
    <% end %>
      <div class="btn-content">
        <%= link_to '検索画面にもどる', search_rooms_path, class:"link back-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="page room-new-page">
  <div class="page-title">
    <h1 class="title-text">ルーム新規作成</h1>
  </div>
  <div class="create-room">
    <span class="explanation">「何たベル？」を使用するには、ルームに所属する必要があります。<br>
    作成済みルームに参加する場合は<%= link_to 'こちら', search_rooms_path, class: "link" %>をクリックしてください。新しくルームを作成する場合は、下記を入力して作成ボタンをクリックします。招待用ルームコードは簡単に特定できない文字を使用しましょう。ルーム作成後は検索用ルームコードをルーム参加者にご連携ください。</span>
    <%= form_with model: @room, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="create-room-form">
        <div class="create-room-form-left">
          <%= f.label :ルーム名, class: "create-room-form-label" %>
          <span class="indispensable">必須</span>
        </div>
        <div class="create-room-form-right">
          <%= f.text_field :room_name, class: "create-room-name", placeholder: "例）鈴木家" %>
        </div>
      </div>
      <div class="create-room-form">
        <div class="create-room-form-left">
          <%= f.label :検索用ルームコード, class: "create-room-form-label" %>
          <span class="indispensable">必須</span>
        </div>
        <div class="create-room-form-right">
          <%= f.text_field :key, class: "create-room-key", placeholder: "8文字以上の半角英数字" %>
        </div>
      </div>
      <div class="create-room-form">
        <div class="create-room-form-left">
          <%= f.label :ルール, class: "create-room-form-label" %>
        </div>
        <div class="create-room-form-right">
          <%= f.text_field :rule, class: "create-room-rule", placeholder: "ルーム内の約束ごとを入力してください" %>
        </div>
      </div>
      <div class='transition-btn'>
        <div class="btn-content">
          <%= f.submit "作成", class:"next-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="page room-search-page">
  <div class="page-title">
    <h1 class="title-text">ルーム検索</h2>
  </div>
  <div class="search-room">
    <span class="explanation">「何たベル？」を使用するには、ルームに所属する必要があります。<br>
    あなたが新規ルームを作成する場合は<%= link_to 'こちら', new_room_path, class: "link" %>をクリックしてください。作成済みルームに参加する場合は、ルームオーナーに検索用ルームコードを確認して、下部に入力してルームを検索してください。</span>
    <%= search_form_for @r, url: join_rooms_path do |f| %>
      <div class="create-room-form">
        <div class="create-room-form-left">
          <%= f.label :key_eq, "検索用ルームコード（完全一致）" %>
        </div>
        <div class="create-room-form-right">
          <%= f.text_field :key_eq, required: true, class: "search-room-key", placeholder: "8文字以上の半角英数字" %>
        </div>
      </div>
      <div class='transition-btn'>
        <div class="btn btn-content">
          <%= f.submit "検索", class:"next-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="page top-page">
  <div class="page-title">
    <h1 class="title-text"><%= "#{@room.room_name}のルーム" %></h1>
  </div>

  <table class="show-table">
    <tbody>
      <tr>
        <th class="show-table-item">オーナー名</th>
        <td class="show-table-value"><%= @room.user.name %></td>
      </tr>
      <tr>
        <th class="show-table-item">ルーム開設日</th>
        <td class="show-table-value"><%= @room.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
    </tbody>
  </table>
  <div class="contents">
    ログインしている状態でルーム参加済みのトップページです。<br>
    メニューの登録、献立の確認、予定登録をすることができます。<br>
    <div class="tab-panel-area">
      <ul class="tab-group">
        <li class="tab tab-A is-active">今日の献立</li>
        <li class="tab tab-B">献立予定登録</li>
        <% if @room.user_id == current_user.id %>
          <li class="tab tab-C">入室承認</li>
        <% end %>
      </ul>
      <div class="panel-group">
        <div class="panel panel-A is-show">
          <% @schedules_today.each do |schedule| %>
            <div>
              <%= image_tag Menu.find(schedule.menu_id).image, class: "index-menu-img" %>
              <%= Menu.find(schedule.menu_id).cook_name %>
            </div>
          <% end %>
        </div>
        <div class="panel panel-B">
          <%= form_with model: [@room, @schedule], url: room_schedules_path(:id), id: 'new_score', class: 'new_score', local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
            <div>
              <div>
                <%= f.label :日付, class: "create-menu-form-label" %>
                <span class="indispensable">必須</span>
              </div>
              <div>
                <%= f.date_field :date, class:"input-default", id:"date", value: Time.now.strftime("%Y-%m-%d") %>
              </div>
            </div>
            <div>
              <div>
                <%= f.label :メニュー, class: "create-menu-form-label" %>
                <span class="indispensable">必須</span>
              </div>
              <div>
                <%= f.collection_select(:menu_id, Menu.where(room_id: @room.id).order(cook_name: "ASC"), :id, :cook_name, {prompt: "選択してください"}, {class:"select-box", id:"menu"}) %>
              </div>
              <div>
                <%= link_to 'メニューを新規登録する', new_room_menu_path(@room.id), class:"link menu-new-btn" %>
              </div>
            </div>
            <div class='transition-btn'>
              <div class="btn-content">
                <%= f.submit "献立登録する" ,class:"next-btn" %><br>
              </div>
            </div>
          <% end %>
        </div>
        <div class="panel panel-C">
          <% if @room.user_id == current_user.id %>
            オーナーのため、承認機能を付与します。<br>
            <% if @applies.present? %>
              <% @applies.each do |apply_user| %>
                <%= apply_user.name %>
                <%= link_to '承認する', approve_rooms_path(apply_user.id), class:"link approve-btn" %>
                <%= link_to '承認しない', reject_rooms_path(apply_user.id), class:"link reject-btn" %>
                <br>
              <% end %>
            <% else %>
              承認待ちのメンバーはいません。
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= calendar events: @schedules do |date, schedules| %>
      <%= date.day %>
      <% schedules.each do |schedule| %>
        <div>
          <%= link_to Menu.find(schedule.menu_id).cook_name, room_menu_path(schedule.menu_id), class: "link menu-name" %>
          <%= link_to "[削除]", room_schedule_path(schedule.id), method: :delete, class: "link delete-link" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/wait.html.erb
<div class="page room-wait-page">
  <div class="page-title">
    <h1 class="title-text">ルーム入室承認待ち</h2>
  </div>
  <% @room.each do |room| %>
    <div class="explanation">
      <%= "ただいま#{room.room_name}のルームに入室申請中です。" %>
    </div>
  <% end %>
  <div class="transition-btn">
    <div class="btn-content">
      <%= link_to '入室申請を取り消す', cancel_rooms_path, class:"delete-btn" %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_main_header.html.erb
<header class='page-header'>
  <div class="header-left">
    <%= link_to "何たベル？", root_path, class: "link logo" %>
  </div>
  <div class="header-right">
    <% if user_signed_in? %>
      <%= link_to current_user.name, "#", class: "link header-link user-name" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "link header-link logout" %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: "link header-link login" %>
      <%= link_to '新規登録', new_user_registration_path, class: "link header-link sign-up" %>
    <% end %>
  </div>
</header>